version: '2'
services:
    refauto-app:
        image: refauto
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://refauto-postgresql:5432/refauto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://refauto-elasticsearch:9200
        ports:
            - 8080:8080
    refauto-postgresql:
        extends:
            file: postgresql.yml
            service: refauto-postgresql
    refauto-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: refauto-elasticsearch
